# Change these first
owner: caarlos0
repo: upptime

# Add your sites here
sites:
  - name: caarlos0.dev
    url: https://caarlos0.dev
  - name: carlosbecker.dev
    url: https://carlosbecker.dev
  - name: carlosbecker.com
    url: https://carlosbecker.com
  - name: goreleaser.com
    url: https://goreleaser.com
  - name: nfpm.goreleaser.com
    url: https://nfpm.goreleaser.com
  - name: starchart.cc
    url: https://starchart.cc
  - name: watchub.pw
    url: http://app.watchub.pw

status-website:
  cname: status.carlosbecker.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: Status
  introMessage: Status Page for several sites run by @caarlos0.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
